<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8" />
        <meta name="generator" content="Pelican" />
        <title>Threading shutdown race condition</title>
        <link rel="stylesheet" href="https://vstinner.github.io/theme/css/main.css" />
        <link href="https://vstinner.github.io/feeds/all.atom.xml" type="application/atom+xml" rel="alternate" title="Victor Stinner blog 3 Atom Feed" />
        <meta name="description" content="This article is about a race condition in threading shutdown that I fixed in Python 3.9 in March 2019. I also forbid spawning daemon threads in..." />
</head>

<body id="index" class="home">
        <header id="banner" class="body">
                <h1><a href="https://vstinner.github.io/">Victor Stinner blog 3</a></h1>
                <nav><ul>
                    <li><a href="https://vstinner.github.io/category/benchmark.html">benchmark</a></li>
                    <li class="active"><a href="https://vstinner.github.io/category/cpython.html">cpython</a></li>
                    <li><a href="https://vstinner.github.io/category/linux.html">linux</a></li>
                    <li><a href="https://vstinner.github.io/category/python.html">python</a></li>
                </ul></nav>
        </header><!-- /#banner -->
<section id="content" class="body">
  <article>
    <header>
      <h1 class="entry-title">
        <a href="https://vstinner.github.io/threading-shutdown-race-condition.html" rel="bookmark"
           title="Permalink to Threading shutdown race condition">Threading shutdown race condition</a></h1>
    </header>

    <div class="entry-content">
<footer class="post-info">
        <abbr class="published" title="2020-04-03T20:00:00+02:00">
                Published: ven. 03 avril 2020
        </abbr>

        <address class="vcard author">
                By                         <a class="url fn" href="https://vstinner.github.io/author/victor-stinner.html">Victor Stinner</a>
        </address>
<p>In <a href="https://vstinner.github.io/category/cpython.html">cpython</a>.</p>
<p>tags: <a href="https://vstinner.github.io/tag/cpython.html">cpython</a> <a href="https://vstinner.github.io/tag/subinterpreters.html">subinterpreters</a> </p>
</footer><!-- /.post-info -->      <p>This article is about a race condition in threading shutdown that I fixed in
Python 3.9 in March 2019. I also forbid spawning daemon threads in
subinterpreters to fix another related bug.</p>
<a class="reference external image-reference" href="https://twitter.com/neeljulien/status/1240292383369150464"><img alt="#CoronaMaison by Julien Neel" src="https://vstinner.github.io/images/coronamaison_jneel.jpg" /></a>
<p>Drawing: <a class="reference external" href="https://twitter.com/neeljulien/status/1240292383369150464">#CoronaMaison by Julien Neel</a>.</p>
<div class="section" id="race-condition-in-threading-shutdown">
<h2>Race condition in threading shutdown</h2>
<div class="section" id="random-test-failure-noticed-on-freebsd-buildbot">
<h3>Random test failure noticed on FreeBSD buildbot</h3>
<p>In March 2019, I noticed that <tt class="docutils literal">test_threading.test_threads_join_2()</tt> was
killed by SIGABRT on the FreeBSD CURRENT buildbot, <a class="reference external" href="https://bugs.python.org/issue36402">bpo-36402</a>:</p>
<pre class="literal-block">
Fatal Python error: Py_EndInterpreter: not the last thread
</pre>
<p>The <tt class="docutils literal">test_threads_join_2()</tt> test <strong>failed randomly</strong> on buildbots when tests
were <strong>run in parallel</strong>, but test_threading <strong>passed</strong> when it was <strong>re-run
sequentially</strong>.  Such failure was silently ignored, since the build was seen
overall as a success.</p>
<p>The test <tt class="docutils literal">test_threading.test_threads_join_2()</tt> was added by in 2013 <a class="reference external" href="https://github.com/python/cpython/commit/7b4769937fb612d576b6829c3b834f3dd31752f1">commit
7b476993</a>.</p>
<p>In 2016, I already reported the same test failure: <a class="reference external" href="https://bugs.python.org/issue27791">bpo-27791</a> (same test, also on FreeBSD). And
Christian Heimes reported a similar issue: <a class="reference external" href="https://bugs.python.org/issue28084">bpo-28084</a>. I simply closed these issues because I
only saw the failure once in 4 months and <strong>I didn't have access to FreeBSD to
attempt to reproduce the crash</strong>.</p>
</div>
<div class="section" id="reproduce-the-race-condition">
<h3>Reproduce the race condition</h3>
<p>In 2019, I had a FreeBSD VM to attempt to reproduce the bug locally.</p>
<p>In June 2019, I found a reliable way to reproduce the bug by <a class="reference external" href="https://github.com/python/cpython/pull/13889/files">adding random
sleeps to the test</a>. With
this patch, I was also able to reproduce the bug on Linux. <strong>I am way more
comfortable to debug an issue on Linux</strong> with my favorite debugging tools!</p>
<p>I identified a race condition in the Python finalization. I also understood
that the bug was not specific to subinterpreters:</p>
<blockquote>
The test shows the bug using subinterpreters (Py_EndInterpreter), but
<strong>the bug also exists in Py_Finalize()</strong> which has the same race condition.</blockquote>
<p>I wrote a patch for <tt class="docutils literal">Py_Finalize()</tt> to help me to reproduce the bug without
subinterpreters:</p>
<pre class="literal-block">
+    if (tstate != interp-&gt;tstate_head || tstate-&gt;next != NULL) {
+        Py_FatalError(&quot;Py_EndInterpreter: not the last thread&quot;);
+    }
</pre>
</div>
<div class="section" id="id1">
<h3>threading._shutdown() race condition</h3>
<p><tt class="docutils literal">threading._shutdown()</tt> uses <tt class="docutils literal">threading.enumerate()</tt> which iterates on
<tt class="docutils literal">threading._active</tt> dictionary.</p>
<p><tt class="docutils literal">threading.Thread</tt> registers itself into <tt class="docutils literal">threading._active</tt> when the
thread starts. It unregisters itself from <tt class="docutils literal">threading._active</tt> when it
completes.</p>
<p>The bug occurs when the thread is unregistered whereas the underlying native
thread is still running and <strong>the Python thread state is not deleted yet</strong>.</p>
<p><tt class="docutils literal">_thread._set_sentinel()</tt> creates a lock and registers a
<tt class="docutils literal"><span class="pre">tstate-&gt;on_delete</span></tt> callback to release this lock. It's called by
<tt class="docutils literal">threading.Thread</tt> when the thread starts to set
<tt class="docutils literal">threading.Thread._tstate_lock</tt>.  This lock is used by
<tt class="docutils literal">threading.Thread.join()</tt> method to wait until the thread completes.</p>
<p><tt class="docutils literal">_thread.start_new_thread()</tt> calls the C function <tt class="docutils literal">t_bootstrap()</tt> which
ends with:</p>
<pre class="literal-block">
tstate-&gt;interp-&gt;num_threads--;
PyThreadState_Clear(tstate);
PyThreadState_DeleteCurrent();
PyThread_exit_thread();
</pre>
<p>When the native thread completes, <tt class="docutils literal">_PyThreadState_DeleteCurrent()</tt> is called:
it calls <tt class="docutils literal"><span class="pre">tstate-&gt;on_delete()</span></tt> callback which releases
<tt class="docutils literal">threading.Thread._tstate_lock</tt> lock.</p>
<p>The root issue is that:</p>
<ul class="simple">
<li><tt class="docutils literal">threading._shutdown()</tt> rely on <tt class="docutils literal">threading._alive</tt> dictionary</li>
<li><tt class="docutils literal">Py_EndInterpreter()</tt> rely on the interpreter linked list of Python thread
states of the interpreter (<tt class="docutils literal"><span class="pre">interp-&gt;tstate_head</span></tt>).</li>
</ul>
<p>The lock on Python thread states (<tt class="docutils literal">threading.Thread._tstate_lock</tt>) and
<tt class="docutils literal">PyThreadState.on_delete</tt> callback were added in 2013 by <strong>Antoine Pitrou</strong>
to Python 3.4, <a class="reference external" href="https://github.com/python/cpython/commit/7b4769937fb612d576b6829c3b834f3dd31752f1">commit 7b476993</a>
of <a class="reference external" href="https://bugs.python.org/issue18808">bpo-18808</a>:</p>
<pre class="literal-block">
Issue #18808: Thread.join() now waits for the underlying thread state
to be destroyed before returning. This prevents unpredictable aborts
in Py_EndInterpreter() when some non-daemon threads are still running.
</pre>
</div>
<div class="section" id="fix-threading-shutdown">
<h3>Fix threading._shutdown()</h3>
<p>Finally in June 2019, I fixed the race condition in <tt class="docutils literal">threading._shutdown()</tt>
with <a class="reference external" href="https://github.com/python/cpython/commit/468e5fec8a2f534f1685d59da3ca4fad425c38dd">commit 468e5fec</a>:</p>
<pre class="literal-block">
bpo-36402: Fix threading._shutdown() race condition (GH-13948)

Fix a race condition at Python shutdown when waiting for threads.  Wait
until the Python thread state of all non-daemon threads get deleted
(join all non-daemon threads), rather than just wait until Python
threads complete.
</pre>
<p>The fix is to modify <tt class="docutils literal">threading._shutdown()</tt> to wait until the Python thread
state of all non-daemon threads get deleted, rather than calling the <tt class="docutils literal">join()</tt>
method of all non-daemon threads. The <tt class="docutils literal">join()</tt> does not ensure that the
Python thread state is deleted.</p>
<p>The Python finalization calls <tt class="docutils literal">threading._shutdown()</tt> to wait until all
threads complete. Only non-daemon threads are awaited: daemon threads can
continue to run after <tt class="docutils literal">threading._shutdown()</tt>.</p>
<p><tt class="docutils literal">Py_EndInterpreter()</tt> requires that the Python thread states of all threads
have been deleted. <strong>What about daemon threads?</strong> More about that in the next
section ;-)</p>
<p>Note: This change introduced a regression (memory leak) which is not fixed yet:
<a class="reference external" href="https://bugs.python.org/issue37788">bpo-37788</a>.</p>
</div>
</div>
<div class="section" id="forbid-daemon-threads-in-subinterpreters">
<h2>Forbid daemon threads in subinterpreters</h2>
<p>In June 2019, while fixing the threading shutdown, I found a reliable way to
trigger a bug with daemon threads when a subinterpreter is finalized:</p>
<pre class="literal-block">
Fatal Python error: Py_EndInterpreter: not the last thread
</pre>
<p>By design, daemon threads can run after a Python interpreter is finalized,
whereas <tt class="docutils literal">Py_EndInterpreter()</tt> requires that all threads completed.</p>
<p>I reported <a class="reference external" href="https://bugs.python.org/issue37266">bpo-37266</a> to propose to
forbid the creation of daemon threads in subinterpreters. I fixed the issue
with <a class="reference external" href="https://github.com/python/cpython/commit/066e5b1a917ec2134e8997d2cadd815724314252">commit 066e5b1a</a>:</p>
<pre class="literal-block">
bpo-37266: Daemon threads are now denied in subinterpreters (GH-14049)

In a subinterpreter, spawning a daemon thread now raises an
exception. Daemon threads were never supported in subinterpreters.
Previously, the subinterpreter finalization crashed with a Pyton
fatal error if a daemon thread was still running.
</pre>
<p>The change adds this check to <tt class="docutils literal">Thread.start()</tt>:</p>
<pre class="literal-block">
if self.daemon and not _is_main_interpreter():
    raise RuntimeError(&quot;daemon thread are not supported &quot;
                       &quot;in subinterpreters&quot;)
</pre>
<p>I commented:</p>
<blockquote>
<strong>Daemon threads must die.</strong> That's a first step towards their death!</blockquote>
<p><strong>Antoine Pitrou</strong> created <a class="reference external" href="https://bugs.python.org/issue39812">bpo-39812: Avoid daemon threads in
concurrent.futures</a> as a follow-up.</p>
<p>In February 2020, when rebuilding Fedora Rawhide with Python 3.9, <strong>Miro
Hrončok</strong> of my team noticed that my change <a class="reference external" href="https://bugzilla.redhat.com/show_bug.cgi?id=1792062">broke the python-jep project</a>. I <a class="reference external" href="https://github.com/ninia/jep/issues/229">reported the bug
upstream</a>. It has been fixed by
using regular threads, rather than daemon threads: <a class="reference external" href="https://github.com/ninia/jep/commit/a31d461c6cacc96de68d68320eaa83e19a45d0cc">commit</a>.</p>
</div>
<div class="section" id="conclusion">
<h2>Conclusion</h2>
<p>A random failure on a FreeBSD buildbot was hiding a severe race condition in
the threading shutdown. The bug existed since 2013, but was silently ignored
since the test passed when re-run.</p>
<p>The race condition was that that the threading shutdown didn't ensure that the
Python thread state of all non-daemon threads are deleted, whereas it is a
<tt class="docutils literal">Py_EndInterpreter()</tt> requirement.</p>
<p>I fixed the threading shutdown by waiting until the Python thread state of all
non-daemon threads is deleted.</p>
<p>I also modified <tt class="docutils literal">Thread.start()</tt> to forbid spawning daemon threads in Python
subinterpreters to fix a related issue.</p>
</div>

    </div><!-- /.entry-content -->

  </article>
</section>
        <section id="extras" class="body">
                <div class="blogroll">
                        <h2>links</h2>
                        <ul>
                            <li><a href="http://vstinner.readthedocs.org/">Victor Stinner's Notes</a></li>
                        </ul>
                </div><!-- /.blogroll -->
                <div class="social">
                        <h2>social</h2>
                        <ul>
                            <li><a href="https://vstinner.github.io/feeds/all.atom.xml" type="application/atom+xml" rel="alternate">atom feed</a></li>

                            <li><a href="https://twitter.com/VictorStinner">Follow @VictorStinner on Twitter</a></li>
                        </ul>
                </div><!-- /.social -->
        </section><!-- /#extras -->

        <footer id="contentinfo" class="body">
                <address id="about" class="vcard body">
                Proudly powered by <a href="https://getpelican.com/">Pelican</a>, which takes great advantage of <a href="https://www.python.org/">Python</a>.
                </address><!-- /#about -->

                <p>The theme is by <a href="https://www.smashingmagazine.com/2009/08/designing-a-html-5-layout-from-scratch/">Smashing Magazine</a>, thanks!</p>
        </footer><!-- /#contentinfo -->

</body>
</html>